[build]
  functions = "functions"
  publish = "/"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"

[functions."getPosts"]
  node_bundler = "esbuild"
  included_files = []
